name: deploy main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  REGISTRY: registry.digitalocean.com
  IMAGE_OWNER: circles-land
  IMAGE_REPOSITORY: pathfinder-updater

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3

      - id: readPackageJson
        run: |
          content=`cat ./package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_REPOSITORY }}
          tags: |
            latest
            {{sha}}
            {{branch}}
            {{base_ref}}
            ${{fromJson(steps.readPackageJson.outputs.packageJson).version}}{{branch}}
            ${{fromJson(steps.readPackageJson.outputs.packageJson).version}}{{base_ref}}

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - 
        name: Install doctl 
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      
      - 
      	name: Log in to DO Container Registry 
        run: doctl registry login --expiry-seconds 600
          
      - 
      	name: Push image to DO Container Registry 
        run: docker push registry.digitalocean.com/my-sample-registry/my-sample-page:${{ github.event.inputs.version }}

      - 
      	name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
