name: deploy main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: readPackageJson
        run: |
          content=`cat package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - name: Build and publish the docker image
        env:
          DOCKER_REGISTRY_USER: ${{secrets.DOCKER_REGISTRY_USER}}
          DOCKER_REGISTRY_PASSWORD: ${{secrets.DOCKER_REGISTRY_PASSWORD}}
        run: |
          docker login https://ghcr.io -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
          docker build -f Dockerfile . --tag ghcr.io/circlesland/pathfinder2-updater:latest --tag ghcr.io/circlesland/pathfinder2-updater:${{fromJson(steps.readPackageJson.outputs.packageJson).version}} --tag pathfinder2-updater --tag master
          docker push ghcr.io/circlesland/pathfinder2-updater:${{fromJson(steps.readPackageJson.outputs.packageJson).version}}
